name: Park Monitor
on:
  schedule:
    - cron: '*/15 * * * *' # 15分おきに自動実行
  workflow_dispatch: # 手動で動かすボタンを表示

jobs:
  run-checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          pip install playwright line-bot-sdk
          playwright install chromium
      - name: Execute script
        env:
          LINE_ACCESS_TOKEN: ${{ secrets.LINE_ACCESS_TOKEN }}
          USER_ID: ${{ secrets.USER_ID }}
        run: python check_park.py
